AWSTemplateFormatVersion: "2010-09-09" 
Description: "Creat EC2 Instance"
Resources:
  ### Parameters ###

Parameters:
  ImageId:
    Type: String
    Default: ""
    Description: "AMI ID for EC2"


  InstanceType:
    Type: String
    Default: "t2.micro"
    Description: "Instance Type"
    AllowedValues: 
      - t2.micro
      - t2.nano
      - t2.small
  
  SubnetId:
    Type: String
    Default: ""
    Description: "SubnetId for EC2"


  SSHKeyName:
    Type: String
    Default: ""
    Description: "ssh key for ec2"

### Resources ###

Resources:
  TestInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      UserData: 
     
        Fn::Base64:
          !Sub |
            #!/bin/bash 
            echo "hello" >> /tmp/myfile
      
      Tags:
        - Key: "Team"
          Value: "BackEnd" 
        - Key: "Name"
          Value: "Test-EC2"
      SecurityGroupIds:
        - sg-05fbbb641109cd795
      KeyName: !Ref SSHKeyName


### Outputs ###

Outputs:
  TestInstance:
    Value: !Ref TestInstance
    Description: "Instance Id"
  TestInstancePublicIP:
    Value: !GetAtt TestInstance.PublicIp
    Description: "Instance Public Ip"




  